---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Correlation Between COVID Cases and Vaccination Status Among Different Age Groups in the U.S.

Mikayla Bolduc^1^ and Shelby Pankratz^2^

^1, 2^ Biosciences Department, Minnesota State University Moorhead

## Abstract

-   Observed data sets of age groups, vaccination status, and number of COVID cases in the U.S.

-   Compared the correlation between vaccination status and number of COVID cases in the U.S.

-   Looked at the rates of vaccination status among different age groups in the U.S.

## Introduction

COVID-19 vaccinations in the U.S. first became available to select populations, such as the elderly and immunocompromised, back in June 2020, right after COVID-19 broke out in March. Fast forward to present day where vaccinations are available to everyone, along with the development of a booster shot. However, since then, vaccines have become a very controversial topic. 

The COVID-19 vaccines were the fastest vaccines to get approved for use. This has led to many people wondering, how effective are these vaccines?

In this project, we will be doing an exploratory data analysis on the relationship between the number of COVID-19 cases and the number of people vaccinated. This will help to show the effectiveness of the vaccine. 

We will be using data from COVID Data Tracker, which is a website managed by the CDC, to look for relationships between positive COVID-19 cases and vaccination status among different age groups. We will be looking at the whole population of the U.S. to get more accurate information on the effectiveness of the COVID-19 vaccine. If the vaccine is effective, we should see that as the number of vaccinated people goes up, the amount of COVID-19 cases will go down. 

## Methods

### Data Acquisition

COVID data: Age Group

1.  Go to <https://covid.cdc.gov/covid-data-tracker/#demographics>
2.  Scroll to "Cases by Age Group"
3.  Click on the Download Tab
4.  Click on Data (.csv)
5.  Save to data folder (cases_by_age_group.csv)

COVID data: Vaccination Status

1.  Go to <https://covid.cdc.gov/covid-data-tracker/#vaccination-demographic>
2.  Scroll to "Age Group" 
3.
4.  Click on the Download Tab
5.  Click on Data (.csv)
6.  Save to data folder (age_groups_of_people_fully_vaccinated.csv)

## Results

## Discussion
We were unable to run a statistical test on this data due to the age groups being different between the different data sets that we used. 

## References/Acknowledgements
We would like to give a big thanks to Dr. Merkord for assisting us with this project. 

